// AUTH
export const REGISTRATION = "REGISTRATION"
export const LOGIN = "LOGIN"
export const AUTH = "AUTH"
export const LOGOUT = "LOGOUT"
export const LOAD_USER = "LOAD_USER"
// TWEETS
export const GET_TWEETS = "GET_TWEETS"
export const ADD_NEW_TWEET = "ADD_NEW_TWEET"
export const DELETE_TWEET = "DELETE_TWEET"
export const SET_TWEET_PINNED = "SET_TWEET_PINNED"
export const LIKE = "LIKE"
export const DISLIKE = "DISLIKE"
export const IS_LIKE_SUCCES = "IS_LIKE_SUCCES"
export const GET_LIKES_TWEETS = "GET_LIKES_TWEETS"
export const UPDATE_AFTER_LIKE = "UPDATE_AFTER_LIKE"
export const GET_ALL_TWEETS_FOLLOW = "GET_ALL_TWEETS_FOLLOW"

// EXPLORE
export const GET_LAST_TWEETS = 'GET_LAST_TWEETS'
export const GET_NEW_USER = 'GET_NEW_USER'
export const GET_MOST_POPULARITY = 'GET_MOST_POPULARITY'


// USERS
export const SEARCH = "SEARCH"
export const GET_USERS_FOR_CONTENT = 'GET_USERS_FOR_CONTENT'
export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const ISLOADING = "ISLOADING"
export const SETTINGS = "SETTINGS"
export const FOLLOW = "FOLLOW"
export const UNFOLLOW = "UNFOLLOW"
export const FOLLOW_DISABLE_BUTTON = "FOLLOW_DISABLE_BUTTON"
export const GET_FOLLOW_LIST = "GET_FOLLOW_LIST"


// SETTINGS
export const MODAL = "MODAL"